import "./globals.css";
import FooterSection from "./section/Footer";

export const metadata = {
  title: "User Management",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <script src="https://cdn.tailwindcss.com"></script>
        <div className="container">{children}</div>
        <FooterSection />
      </body>
    </html>
  );
}
